pub mod acos_gate;
pub mod asin_gate;
pub mod atan_gate;
pub mod cos_gate;
pub mod cosh_gate;
pub mod sin_gate;
pub mod sinh_gate;
pub mod tan_gate;
pub mod tanh_gate;

pub use acos_gate::*;
pub use asin_gate::*;
pub use atan_gate::*;
pub use cos_gate::*;
pub use cosh_gate::*;
pub use sin_gate::*;
pub use sinh_gate::*;
pub use tan_gate::*;
pub use tanh_gate::*;
